### ISSUE TITLE
Incorrect abbreviation for the category of "Object Name."

### ISSUE THREAD

**Issue by gaiusyu** [ginolzh/Variable_Aware_Log_Abstraction#3]
Thank you for openly sharing the relevant data. Your work is excellent.! In the README file, it seems that "Object Name" should not belong to the same category as "Object Amount" under "OBA." According to your paper, "Object Name" should be categorized under "OBN."

**Comment by ginolzh** [comment]
Thank you for the correction, it was a typo in the readme file. We have corrected it : )
